### PR TITLE
Instruct to first configure, before registering the first user – mention...

### PR DESCRIPTION
**Pull request by sanduhrs**
...ing the needed settings.

### CODE REVIEW

**Comment by sanduhrs** [comment]
Also see #488

**Comment by ryansmith94** [comment]
Thanks for the pull request @sanduhrs. I've made a couple of comments on the commit. I think it might be useful if LearningLocker/learninglocker#488 was linked to in the docs. Maybe this link can go on the text "change the value for key".

**Comment by sanduhrs** [comment]
What is best practice for the storage folder – change ownership to webserver user or just give read/write access to everyone?
For the full folder `app/storage` or just the folders inside?

**Comment by ht2** [comment]
Hi @sanduhrs,

Typically what I would suggest (on Apache at least) is to add the apache user to the same group as the owner of the storage folder. You can then use the following to set owner/group read/write permissions for dirs and files on the relevant location (in the example below `app/storage`) without affecting public read/write permissions

`sudo find app/storage/ -type d -exec chmod 775 {} + && sudo find app/storage/ -type f -exec chmod 664 {} +`

**Comment by ht2** [comment]
Sorry - didn't mean to close!

**Comment by ryansmith94** [comment]
Thanks @sanduhrs! This looks good to me. I might make a few cosmetic changes after merging.

**Comment by ryansmith94** [comment]
Sorry it has taken so long to get to this, we've had a lot on here the past month.

**Pull request merged**
